### ISSUE TITLE
raft_test doesn't Step through messages generate by Raft.tick()?

### ISSUE THREAD

**Issue by schneiderlin** [talent-plan/tinykv#160]
from what I understant both local messages and network messages should be append into Raft.msgs, and some code is responsible for loop through Raft.msgs and call Raft.Step.
Is that correct?

so the local messages(MessageType_MsgHup and MessageType_MsgBeat) generate by Raft.tick() just sit in msgs, waiting to be process, until then it's state will not change.

if that is the case, the following code will not terminate
https://github.com/pingcap-incubator/tinykv/blob/1df74d600cb0c5001f32d2d21d6f89e9744ee3e0/raft/raft_test.go#L797-L799
https://github.com/pingcap-incubator/tinykv/blob/1df74d600cb0c5001f32d2d21d6f89e9744ee3e0/raft/raft_test.go#L853-L855

**Comment by Connor1996** [comment]
PTAL @NingLin-P

**Comment by NingLin-P** [comment]
> from what I understant both local messages and network messages should be append into Raft.msgs, and some code is responsible for loop through Raft.msgs and call Raft.Step.
> Is that correct?

Actually, `Raft.msgs` only contains messages that this raft peer wants to send out, for local messages and received messages, `Raft.Step` will be called by the user.

**Comment by schneiderlin** [comment]
Thank you for replying! Appreciate it
