### ISSUE TITLE
TestRawDelete1 in server_test doesn't prepare test data

### ISSUE THREAD

**Issue by FK2469** [talent-plan/tinykv#161]
In [TestRawDelete1](https://github.com/pingcap-incubator/tinykv/blob/1df74d600cb0c5001f32d2d21d6f89e9744ee3e0/kv/server/server_test.go#L176), we didn't prepare test data before we delete it.

**Comment by Connor1996** [comment]
Nice catch, it was deleted by mistake. 
Please help add it
``` go
	assert.Nil(t, Set(s, cf, []byte{99}, []byte{42}))
```
