### ISSUE TITLE
message from old term should ignore or not?

### ISSUE THREAD

**Issue by xiongjiwei** [talent-plan/tinykv#165]
In file `raft_test.go` (line 535) `TestHandleMessageType_MsgAppend2AB` test case 8 and 9.
The message term is 1, and they are sent to a follower which in term 2, and expected the follower could append them and update state. From what I understand, I think this message should be ignore because this two message's term is slower than the follower. someone can explain this? thx. :)

**Comment by Connor1996** [comment]
Actually, it should be ignored. But this test just checks the logic of `handleAppendEntires`, so it skips checking the term of messages which is done in `Step()`.

The term is a little confusing, could you help change it to 2?

**Comment by schneiderlin** [comment]
I have another question. why test case 8 wCommit is 1 instead of 2? follower's last index is 2, and leader's commit is 3, min(2, 3) = 2

**Comment by xiongjiwei** [comment]
> I have another question. why test case 8 wCommit is 1 instead of 2? follower's last index is 2, and leader's commit is 3, min(2, 3) = 2

I think it is because Leader's commit is 3, but he didn't send any entries to follower, so follower just konw index 1 is able to commit, but have no knowledge about how to do with index 2.
