### ISSUE TITLE
TestLeaderElectionOverwriteNewerLogs2AB forget to setup peers information?

### ISSUE THREAD

**Issue by schneiderlin** [talent-plan/tinykv#171]
https://github.com/pingcap-incubator/tinykv/blob/edb12af93f17321030036ffcfcc7723239c3f8ad/raft/raft_test.go#L121
should be something like
`
cfg := func(c *Config) {
		c.peers = idsBySize(5)
	}
`

**Comment by NingLin-P** [comment]
The peer information will be setup inside `newNetworkWithConfig`, but `var cfg func(*Config)` looks confusing and can be replaced with `nil`, would you mind making a PR to fix it?

**Comment by schneiderlin** [comment]
but in this case, before `newNetworkWithConfig`, 5 raft nodes are already created with no peers
https://github.com/pingcap-incubator/tinykv/blob/edb12af93f17321030036ffcfcc7723239c3f8ad/raft/raft_test.go#L137-L141

**Comment by NingLin-P** [comment]
Got it, thank you! The tests rely on `newNetworkWithConfig` to directly modify the raft's state when setup, which is conflict with the definition of `newRaft`, and we should let `newRaft` control the setup. Changing `var cfg func(*Config)` to `cfg := func(c *Config) { c.peers = idsBySize(5) }`, and remove the following codes can fix it.
https://github.com/pingcap-incubator/tinykv/blob/edb12af93f17321030036ffcfcc7723239c3f8ad/raft/raft_test.go#L1597-L1600
