### ISSUE TITLE
shall we expose ErrKeyNotFound error when we invoke GetCF Method ?

### ISSUE THREAD

**Issue by 0XFF-96** [talent-plan/tinykv#173]
I encountered a pitfall in  `kv/server/server_test.go`

### Firstly
the test case `TestRawGetAfterRawDelete1`  in line 169 says we need to expose ErrKeyNotFound err when we try to get a non-exists key. 

```golang
	resp, err := server.RawGet(nil, get)
	assert.Nil(t, err)
	assert.True(t, resp.NotFound)
```

### Secondly
the code in `TestRawDelete1` says we should return nil when we try to get a key that have already beed deleted. 

```golang
	_, err := server.RawDelete(nil, req)
	assert.Nil(t, err)
	val, err := Get(s, cf, []byte{99})
	assert.Equal(t, nil, err)
	assert.Equal(t, []byte(nil), val)
```

### In the end 
I am able to pass the `make project1` when I change this line .
from 
```
	assert.Equal(t, nil, err)
```
to 
```
	assert.Equal(t, badger.ErrKeyNotFound, err)
```

### What I want to know 

So, I wonder it this a bug ? or there is a missing part of my code that I should continue to implement ?

**Comment by fengzixu** [comment]
Please pull the latest code. If you delete a non-exist key, GetCF shouldn't return the error. You should change your implementation of GetCF

**Comment by Connor1996** [comment]
in the lastest code, we assume that val == "" indicates key not found.

**Comment by 0XFF-96** [comment]
thanks for helping
