### ISSUE TITLE
running `go mod tidy` or `make project1` gives me an error

### ISSUE THREAD

**Issue by mdlfop** [talent-plan/tinykv#174]
go version go1.14.3 linux/amd64
I receive the following error when I run any of the above commands: 
> go: github.com/pingcap/tidb@v1.1.0-beta.0.20200309111804-d8264d47f760 requires
        github.com/pingcap-incubator/tinykv@v0.0.0-20200320061650-f660f803e910: invalid version: unknown revision f660f803e910

**Comment by Connor1996** [comment]
can't reproduce, are you sure it's the latest `course` branch?

**Comment by mdlfop** [comment]
Yes. I am on the latest commit on the `course` branch. I also tried on another computer and I still receive the same error message. Thanks.  The error message when I run `make project1`:
> GO111MODULE=on go test -v --count=1 --parallel=1 -p=1 ./kv/server -run 1
go: github.com/pingcap/tidb@v1.1.0-beta.0.20200309111804-d8264d47f760 requires
	github.com/pingcap-incubator/tinykv@v0.0.0-20200320061650-f660f803e910: invalid version: unknown revision f660f803e910
make: *** [Makefile:54: project1] Error 1

**Comment by Connor1996** [comment]
`github.com/pingcap/tidb@v1.1.0-beta.0.20200309111804-d8264d47f760`  seems an old version, not the same as the one in the latest commit.

**Comment by mdlfop** [comment]
Thanks @Connor1996 . I still believe I am using the latest commit of the branch. I have created a google colab notebook showing the things I have done. Please take a look at it. (I still get the same errors here as well) https://colab.research.google.com/drive/16dSBPQ4ekB2e0nCQn4xjhJSwQSl0uBdi?usp=sharing

**Comment by Connor1996** [comment]
You're right. It's due to the modcache. After running `go clean -modcache`, I can reproduce it. Let me take a look.

**Comment by Connor1996** [comment]
Fix it. Please try again.

**Comment by mdlfop** [comment]
It works! Thanks a lot :)
