### ISSUE TITLE
`newTestPeerStorageFromEnts` not modify applyState in memory, only in DB

### ISSUE THREAD

**Issue by schneiderlin** [talent-plan/tinykv#176]
it only changes applyState in DB
https://github.com/pingcap-incubator/tinykv/blob/1df74d600cb0c5001f32d2d21d6f89e9744ee3e0/kv/raftstore/peer_storage_test.go#L34-L40

but provided function `PeerStorage.truncatedIndex` and `PeerStorage.truncatedTerm` is using in memory `applyState`
https://github.com/pingcap-incubator/tinykv/blob/1df74d600cb0c5001f32d2d21d6f89e9744ee3e0/kv/raftstore/peer_storage.go#L219-L221

so in `TestPeerStorageTerm` test 2 and 3, `Term` will return `ErrCompacted`, since truncatedIndex is initially 5

should we modify `PeerStorage.truncatedIndex` and `PeerStorage.truncatedTerm` function?

**Comment by NingLin-P** [comment]
Thanks for reporting this issue!
> should we modify `PeerStorage.truncatedIndex` and `PeerStorage.truncatedTerm` function?

The way of how to read the `applyState` depends on how `applyState` in update (in the implement of `HandleRaftReady`), how do you think @Connor1996 ?

**Comment by Connor1996** [comment]
@NingLin-P I think it's okay to give them the implementation because there is a `applyState` field in the `PeerStorage`

I think the root cause is `applyState` and `raftState` is not a pointer, so it doesn't update it as expected. Would you mind changing it? @schneiderlin
