### ISSUE TITLE
region meta in Scheduler and TinyKV has same address

### ISSUE THREAD

**Issue by xiongjiwei** [talent-plan/tinykv#177]
https://github.com/pingcap-incubator/tinykv/blob/1df74d600cb0c5001f32d2d21d6f89e9744ee3e0/kv/test_raftstore/scheduler.go#L345-L348
From the code, it seems that region meta in Scheduler and TinyKV should be independence. 
https://github.com/pingcap-incubator/tinykv/blob/1df74d600cb0c5001f32d2d21d6f89e9744ee3e0/kv/raftstore/peer.go#L345-L352
but it send a pointer to scheduler. It will cause problem when change peer. Maybe it should be cloned first.

**Comment by Connor1996** [comment]
good catch~ Mind sending a PR to fix it?
