### ISSUE TITLE
code may cause redundant change peer requsest

### ISSUE THREAD

**Issue by xiongjiwei** [talent-plan/tinykv#182]
https://github.com/pingcap-incubator/tinykv/blob/b6d7c442e3c9d1eac7192c3bff8372b16a7ae18b/kv/test_raftstore/scheduler.go#L393-L406
code between 396 and 401 does not make sense, it will always return false unless it is so lucky that the first peer in region is the added peer. Also, if there is no peer in region or only one peer that is added peer, code will reach the unreachable part.

**Comment by Connor1996** [comment]
you're right, seems should write like this:
```go
       for _, p := range region.GetPeers() { 
 		if add.peer.GetId() == p.GetId() { 
 			add.pending = true
                        return false 
 		} 
 	} 
 	// TinyKV rejects AddNode. 
 	return false 
```

**Comment by xiongjiwei** [comment]
> you're right, seems should write like this:
> 
> ```go
>        for _, p := range region.GetPeers() { 
>  		if add.peer.GetId() == p.GetId() { 
>  			add.pending = true
>                         return false 
>  		} 
>  	} 
>  	// TinyKV rejects AddNode. 
>  	return false 
> ```
`add.pending = true` does not effect op。 add `op.Data = add` or use pointer to Data in Operator
