### ISSUE TITLE
`TestRawNodeRestart2AC` & `TestRawNodeRestartFromSnapshot2C` expected result don't have softstate and hardstate

### ISSUE THREAD

**Issue by schneiderlin** [talent-plan/tinykv#190]
DeepEqual will fail because `want` and `rd` differ in softstate and hardstate.

maybe we need something like
```
want := Ready{
		&SoftState{
			Lead:      None,
			RaftState: StateFollower,
		},
		pb.HardState{
			Term:   st.Term,
			Commit: st.Commit,
		},
		[]pb.Entry{},
		pb.Snapshot{},
		// commit up to commit index in st
		entries[:st.Commit],
		make([]pb.Message, 0), // Messages []pb.Message should be empty slice or nil?
	}
```

**Comment by NingLin-P** [comment]
DeepEqual is very restricted to what returns from `rawNode.Ready()`, and limit how people to implement it, do you have any idea to avoid it? @Connor1996

**Comment by Connor1996** [comment]
have no better idea.

what do you mean by `differ in softstate and hardstate.` @schneiderlin

**Comment by schneiderlin** [comment]
`want` only set 2 fields. 
https://github.com/pingcap-incubator/tinykv/blob/1df74d600cb0c5001f32d2d21d6f89e9744ee3e0/raft/rawnode_test.go#L194-L198

and `rd` should contain hard state
https://github.com/pingcap-incubator/tinykv/blob/1df74d600cb0c5001f32d2d21d6f89e9744ee3e0/raft/rawnode_test.go#L192

`want` soft state is nil and `rd` soft state should be
```
&SoftState{
  Lead:      None,
  RaftState: StateFollower,
}
```

**Comment by Connor1996** [comment]
sorry for late response.
As comment said 
```
type Ready struct {
        // SoftState will be nil if there is no update.
	*SoftState
	// HardState will be equal to empty state if there is no update.
        pb.HardState
        ...
}
```
In this case, the result is expected to include softstate and hardstate

**Comment by schneiderlin** [comment]
sorry didn't see the comment, close now
