### ISSUE TITLE
should heartbeat RPC update commit?

### ISSUE THREAD

**Issue by schneiderlin** [talent-plan/tinykv#191]
`TestHandleHeartbeat2AA` expect commit would change.

but later I encounter a bug like this
- an old leader is separate away and receives a log(assume index 10) from a client(no chance to commit).
- while the majority elect a new leader and commit is up to index 15.
- when the old leader comes back to the cluster and receives a heartbeat RPC says commit is 15, it will apply the wrong log index 10(this log should be overwritten).

**Comment by NingLin-P** [comment]
Yes, `heartbeat` RPC should update the commit index, and to avoid the situation you mentioned here, it very depends on the implementation of how to setting the `m.Commit` in `MsgHeartbeat` when send requests and how `handleHeartbeat` handle it, or you can do some check like: is there are log at `m.Commit` index and match the term of `m.Term` before change the commit index. Also, the test assumes all the work should be done at the `handleHeartbeat` and a better place should be `raft.Step()` and there should be test case cover the situation you mentioned here,  would you like to send a pr to fix it?
