### ISSUE TITLE
What does storage.Start() do

### ISSUE THREAD

**Issue by sdjdd** [talent-plan/tinykv#195]
I think this function initializes storage, but it is not called in `kv/server/server_test.go`. So what does this function do?

**Comment by Connor1996** [comment]
Start() is of no use for `StandaloneStorage`, but it will be called by `RaftStorage`.

Would you mind making a PR to add missing `Start()` for the tests to make it not confusing?

**Comment by sdjdd** [comment]
yes, my pleasure.
