### ISSUE TITLE
Snapshot will always unavailable if error occur when generate snapshot

### ISSUE THREAD

**Issue by xiongjiwei** [talent-plan/tinykv#198]
https://github.com/pingcap-incubator/tinykv/blob/d13ccb8785702ecdf17368bf2350f7f82c58cab5/kv/raftstore/runner/region_task.go#L81-L88
https://github.com/pingcap-incubator/tinykv/blob/d13ccb8785702ecdf17368bf2350f7f82c58cab5/kv/raftstore/peer_storage.go#L157-L162

`ps.snapState.Receiver` will never recive msg if error happend. `Snapshot` method will always return `ErrSnapshotTemporarilyUnavailable`

**Comment by Connor1996** [comment]
I think it's expected to return `ErrSnapshotTemporarilyUnavailable` when it failed to generate snapshot

**Comment by xiongjiwei** [comment]
> I think it's expected to return `ErrSnapshotTemporarilyUnavailable` when it failed to generate snapshot

@Connor1996 but `ErrSnapshotTemporarilyUnavailable` cannot distinguish snapshot is on generating or generate failed cause both these two situation will not send msg to notifier

**Comment by Connor1996** [comment]
if it failed to generate, will return err finally
https://github.com/pingcap-incubator/tinykv/blob/d13ccb8785702ecdf17368bf2350f7f82c58cab5/kv/raftstore/peer_storage.go#L175-L177

**Comment by xiongjiwei** [comment]
> if it failed to generate, will return err finally
> https://github.com/pingcap-incubator/tinykv/blob/d13ccb8785702ecdf17368bf2350f7f82c58cab5/kv/raftstore/peer_storage.go#L175-L177

@Connor1996 when first time call `Snapshot` it will set `ps.snapState.StateType` to `snap.SnapState_Generating` and return `ErrSnapshotTemporarilyUnavailable`. if failed to generate, select will always match default and return `ErrSnapshotTemporarilyUnavailable`. code below has no chance to run
https://github.com/pingcap-incubator/tinykv/blob/d13ccb8785702ecdf17368bf2350f7f82c58cab5/kv/raftstore/peer_storage.go#L174-L177
I change code to make generate snapshot always failed, and `Snapshot` always return `ErrSnapshotTemporarilyUnavailable`

**Comment by Connor1996** [comment]
Oh, you're right. Seems we can return nil to channel when failed to generate the snapshot.
