### ISSUE TITLE
snapshot did not close file after using

### ISSUE THREAD

**Issue by xiongjiwei** [talent-plan/tinykv#199]
https://github.com/pingcap-incubator/tinykv/blob/d13ccb8785702ecdf17368bf2350f7f82c58cab5/kv/raftstore/snap/snap.go#L379-L385

this part is using for building snapshot, it opens metafile and 3 cf files, but it seems the files did not closed.  Also, in `NewSnapForSending`, `NewSnapForReceiving`, `NewSnapForApplying` are not close file too. 
Or, these files has been closed and I miss something?

**Comment by Connor1996** [comment]
seems you're alright. I forget to close the files
