### ISSUE TITLE
eraftpb.pb.go fileDescriptor inconsistence

### ISSUE THREAD

**Issue by OneSizeFitsQuorum** [talent-plan/tinykv#203]
I used `make proto` locally, then I used `git status` to check if any files have been modified,and the eraftpb.pb.go is the only one.As shown in the figure below,I found that the fileDescriptor of eraftpb.proto generated by protoc has been changed from 6ff387e2d76c3034 to 2f2e0bcef614736b.
![image](https://user-images.githubusercontent.com/32640567/84016608-19c68400-a9b0-11ea-9526-562f4cff156a.png)
Actually I think these generated code should not be pushed to git repo,but as you have pushed these files,is it better to make them consistent?Do I need to fix this?Or this is just because the difference of environment?

**Comment by Connor1996** [comment]
Update it in latest commit, though it's okay.
