### ISSUE TITLE
Corrupted snap files due to hard linking received snapshots

### ISSUE THREAD

**Issue by junlong-gao** [talent-plan/tinykv#218]
When I worked on a solution, sometimes I get error related to applying snapshot, complaining some of the sst files are of invalid size 0.

This is strange as snapshots are validated on reception. If it passes reception, it should not have an invalid size.

After digging into the snapshot applying code path, I noticed that DB.IngestExternalFiles is just hardlinking the sst files into badger without removing the received file here:
https://github.com/pingcap-incubator/tinykv/blob/fc36c301fbf92d05e30e629453a7c3282399af75/kv/raftstore/snap/snap.go#L692

so what can happen is sst files are getting compacted as part of lsm compaction, and its size is reduced to 0 (so compaction literally does unmap/truncate to free space I assume?). when snapshot is re-sent, the follower will find the snapshot already exists. then when the follower applies the snapshot, it blows up on size mismatch.

we should either:
1. make a copy when applying the snapshot, or better
2. remove the link after ingesting the snapshot file (and the entire snapshot file info including the manifest)?

I did approach 1) in my solution: 
https://github.com/junlong-gao/tinykv/blob/0fc6c28acffee911a38b2c043809e6977d7d2822/kv/raftstore/snap/snap.go#L692 
and the issue no longer surfaces. 

Could pingcap team please take a look at this and validate if my theory here makes sense?

**Comment by woodgear** [comment]
sounds familiar, i meet this error either.but in the end. i find the reason is it reapply the same snapshot (i forgot to cancel pending snapshot in advance).

**Comment by Connor1996** [comment]
Maybe it is due to the same reason as @woodgrear's? It is not supposed to apply one snapshot twice.

**Comment by junlong-gao** [comment]
Thanks for the feedback. I will examine the point from @woodgear  and report back if it was the issue before I close it.
