### ISSUE TITLE
Access global context is racy

### ISSUE THREAD

**Issue by junlong-gao** [talent-plan/tinykv#219]
for example, storeMeta is accessed in both newRaftWorker (mutation for conf change) and newStoreWorker (reading for heartbeating to pd):

https://github.com/pingcap-incubator/tinykv/blob/fc36c301fbf92d05e30e629453a7c3282399af75/kv/raftstore/raftstore.go#L91

I was working on a solution and noticed inconsistent region info was sent to the scheduler (peer and region epoch field in the storeMeta was inconsistent) probably due to the fact that I was mutating it in place, updating fields one after another, and heartbeat worker reads seeing 2 fields one before and one after the mutation.

I avoided this issue in my solution by doing a deep copy:

https://github.com/junlong-gao/tinykv/blob/0fc6c28acffee911a38b2c043809e6977d7d2822/kv/raftstore/peer_msg_handler.go#L79

yet it is still racy.

Perhaps we should kindly add a mutex in the global context so folks working on this will notice the race condition here?

**Comment by Connor1996** [comment]
Please update to the latest commit, there is a mutex already.  See https://github.com/pingcap-incubator/tinykv/commit/abaa565b18e488ca7464d1da0c156f15b71e66f7

**Comment by junlong-gao** [comment]
got it, thanks!
