### ISSUE TITLE
fix test bug

### ISSUE THREAD

**Issue by zhuo1angT** [talent-plan/tinykv#225]
```
func TestPeerStorageTerm(t *testing.T) {
	ents := []eraftpb.Entry{
		newTestEntry(3, 3), newTestEntry(4, 4), newTestEntry(5, 5), // <<<<<<<-------------------------
	}
	tests := []struct {
		idx  uint64
		term uint64
		err  error
	}{
		{2, 0, raft.ErrCompacted},
		{3, 3, nil},
		{4, 4, nil},
		{5, 5, nil},
	}
	for _, tt := range tests {
		peerStore := newTestPeerStorageFromEnts(t, ents)
		term, err := peerStore.Term(tt.idx)
		if err != nil {
			assert.Equal(t, tt.err, err)
		} else {
			assert.Equal(t, tt.term, term)
		}
		cleanUpTestData(peerStore)
	}
}
```

In this test, entries [3, 3], [4, 4], [5, 5] were passed to init the `peerstorage`.
But in fact, all newly created peerstorage have entries index & term starting with 5.

I think the writer of this test function assumes that all entries slices pass to the `ps.Append` function are  committed by the Raft group, but instead, I checked the entry index in the append function and refused it, so i failed the test.

I think it is better to change the hard-encoded entries to [6, 6], [7, 7], [8, 8].

**Comment by NingLin-P** [comment]
Thanks @zhuo1angT , I think the tests assume `newTestPeerStorageFromEnts` is initializing the `PeerStorage` from the passed entries instead of initializing the `PeerStorage` with the default index 5 & term 5

**Comment by zhuo1angT** [comment]
> Thanks @zhuo1angT , I think the tests assume `newTestPeerStorageFromEnts` is initializing the `PeerStorage` from the passed entries instead of initializing the `PeerStorage` with the default index 5 & term 5

The test generates a `PeerStorage` with everything set to 5, afterwards, it calls the self-implemented function `ps.Append`, if there's a check on whether the index & the term is valid (in the `ps.Append` function), the following test just fails. 
I think it is reasonable to make the check since the entries slice might not be appropriate.

**Comment by NingLin-P** [comment]
What I mean is that `newTestPeerStorageFromEnts` is an inner function to construct `PeerStorage` like `newTestPeerStorage` but not setting everything to 5 and instead initializing the `PeerStorage` with the passed entries (as its name imply). But, as the issue you mentioned still exist, we may need to change `newTestPeerStorageFromEnts`, perhaps we need to clear the `PeerStorage`'s `RaftLocalState` and `ApplyState` and then calling `ps.Append`. What do you think? @zhuo1angT

**Comment by zhuo1angT** [comment]
Yes, I think the intention of function `newTestPeerStorageFromEnts` is clear, but actually it behaves set things to 5.
For my case, simply changing the test case itself works things out and lets me pass the test. In my humble opinion, stick to the test case with Entry whose term less than 5 might be misleading (When I first read the document of `Project 2B`, the reason why it should set the term & index to 5 confuses me).

**Comment by zhuo1angT** [comment]
BTW, I found these test cases after I passed 2B and run it with `make test`. In a previous issue #188 , someone has mentioned before that these cases are not with the suffix `2B` so that it can not be check within `make project2B` or `make project2`.
I think maybe it's the time to bring this in?

/cc @NingLin-P

**Comment by NingLin-P** [comment]
> For my case, simply changing the test case itself works things out and lets me pass the test.

Changing the test case would be the simplest way to get a workaround with this issue, but IMO it is quite not intuitive as initializing `PeerStorage` with everything set to 5 is the requirement of the upper layer, and should not happen on the unit test (these tests didn't test the `5` behavior), I think a more complete way to fix this issue is to write another `NewPeerStorageFromZore` which set everything to 0 and use it at the test.

> BTW, I found these test cases after I passed 2B and run it with make test. In a previous issue #188 , someone has mentioned before that these cases are not with the suffix 2B so that it can not be check within make project2B or make project2.
I think maybe it's the time to bring this in?

Yes, let's do it.
