### ISSUE TITLE
Engines.Close semantics in project 1

### ISSUE THREAD

**Issue by yujqiao** [talent-plan/tinykv#232]
https://github.com/tidb-incubator/tinykv/blob/4b02c82dac42893ffc140d3628a70860c1147729/kv/util/engine_util/engines.go#L40-L48

In project 1, the raft engine is not required. So the learner has to comment out lines of closing `en.Raft` or pass a faked closeable struct.
In my case, I pass `nil` to `en.Raft` and the program panicked because of closing a `nil` pointer. And I surrounded these lines with `if en.Raft != nil`.

In project 1, I don't think it's a good idea to enforcing the learner to alter files other than `server.go` and `standalone_storage.go`. Or the other way, providing a faked closable struct in `server.go` to `en.Raft` seems tedious and unnecessary to me. In fact, in the project1, the learner shouldn't care about the raft engine at all.

Any thoughts? I would suggest surrounding these lines with an `if` sentence to fix the null pointer issue and don't bother learners in project 1.

**Comment by Connor1996** [comment]
This isn't intended to be used for project 1
