### ISSUE TITLE
Tests call newLog with improperly initialized storage

### ISSUE THREAD

**Issue by yujqiao** [talent-plan/tinykv#234]
https://github.com/tidb-incubator/tinykv/blob/5dcdd7bfcbcfa0a28c1d7a1eb171d9c124127f84/raft/raft_test.go#L632

The line here, and many others,  call `newLog` with a `MemoryStorage`, but leave `snapShot` empty. Sure the field won't really be used in project2a. But if a student wants to read `Storage.HardState` by calling `Storage.InitialState` in `newLog` to initialize `RaftLog.committed`, he will get a panic.

Because 

https://github.com/tidb-incubator/tinykv/blob/5dcdd7bfcbcfa0a28c1d7a1eb171d9c124127f84/raft/storage.go#L96-L99

Here will try to dereference `ms.snapshot.Metadata.ConfState`, which is an uninitialized nil pointer.

The panic can be worked around if the student only read HardState in `newRaft`. But it's totally valid to read it in `newLog` since it's part of the parameter, and the callee should be able to read the parameter as it wants.

I propose changes like this to avoid the panic:
```go
// InitialState implements the Storage interface.
func (ms *MemoryStorage) InitialState() (pb.HardState, pb.ConfState, error) {
    if ms.snapshot == nil {
	return ms.hardState, nil, ErrSnapshotTemporarilyUnavailable
    } else {
	return ms.hardState, *ms.snapshot.Metadata.ConfState, nil
    }
}
```

**Comment by Connor1996** [comment]
PTAL @NingLin-P

**Comment by NingLin-P** [comment]
Sorry for the delay @Rapiz1 

With the changes you proposed, we still can't initialize `RaftLog.committed` in this case, because `Storage.InitialState` will return a non-`nil` error.

Instead, I think we can provide something like:
```
func NewMemoryStorageWithEnts(ents []pb.Entry) *MemoryStorage {
	return &MemoryStorage{
		ents,
		snapshot: pb.Snapshot{Metadata: &pb.SnapshotMetadata{ConfState: &pb.ConfState{}}},
	}
}
```
and replace `newLog(&MemoryStorage{ents: ...}` with `newLog(&NewMemoryStorageWithEnts(ents))`, how do you think? @Rapiz1

**Comment by yujqiao** [comment]
@NingLin-P I think you made a good point

**Comment by NingLin-P** [comment]
@Rapiz1  Would you like to send a PR to fix this issue? 🤣
