### ISSUE TITLE
'find no region for' panic.

### ISSUE THREAD

**Issue by yujqiao** [talent-plan/tinykv#241]
When running various tests from 2b~2c, I randomly come across 'find no region for xxxx' panic. Not every time, but frequently.
Changing `SleepMS(20)` to `SleepMS(40)` fixed the issue. Changing to `SleepMS(5)` I can reproduce the panic every time.
https://github.com/tidb-incubator/tinykv/blob/a79bebf4397b70c8d40a6d266e296da8b12c2eb0/kv/test_raftstore/cluster.go#L265-L276

I wonder how is the time interval determined here? I suppose there's another thread running raft and the test should wait a while to get the correct result. So with a slower machine, the time interval should be larger.
If my assumption is true, this should be documented.

Or I'm wrong. And all because of bugs in my code. Then the issue should be closed.

> CPU: Intel i7-6600U
> Host: ThinkPad T460s

**Comment by Connor1996** [comment]
I think 2s is large enough. Probably, it's due to your code doesn't send out the region heartbeat in time.

**Comment by yujqiao** [comment]
I took a closer look at the code of the test driver. By "region heartbeat" you should mean `SchedulerRegionHeartbeatTask`, right? But I suppose it's all issued by the test driver. Can you provide more detail about "your code doesn't send out the region heartbeat in time."? I suppose in 2b there's no such a thing called region heartbeat for students to implement, just the heartbeat RPC of raft.

**Comment by Connor1996** [comment]
The region heartbeat will be triggered by the test driver every 100ms on the leader, please check if the raft elects a leader successfully in time.

**Comment by yujqiao** [comment]
A bug causes leader changes frequently. So sometimes the test driver can't find the region.
