### ISSUE TITLE
Tests send AppendEntriesResponse with term 0

### ISSUE THREAD

**Issue by yujqiao** [talent-plan/tinykv#244]
https://github.com/tidb-incubator/tinykv/blob/eb173f0df1645d84719e9f3c0e95927ad8f250a8/raft/raft_test.go#L1193-L1198

Here send an `AppendEntriesResponse` with term 0, which should be ignored because of an outdated term. But it intends to send a valid message with term `r.Term`

**Comment by NingLin-P** [comment]
Nice catch! We should set the `term` of a message if it is not a local message (`MsgHup`, `MsgBeat`, `MsgPropose` and `MsgTransferLeader`), besides this place, I also found: 
https://github.com/tidb-incubator/tinykv/blob/eb173f0df1645d84719e9f3c0e95927ad8f250a8/raft/raft_test.go#L1409-L1418

https://github.com/tidb-incubator/tinykv/blob/eb173f0df1645d84719e9f3c0e95927ad8f250a8/raft/raft_test.go#L1312

Would you like to send a PR fix it? @Rapiz1

**Comment by yujqiao** [comment]
OK. I will find time to fix it
