### ISSUE TITLE
PeerId and StoreId in TestBasicConfChange3B

### ISSUE THREAD

**Issue by yujqiao** [talent-plan/tinykv#248]
https://github.com/tidb-incubator/tinykv/blob/2546def36e29b5b14c7fbf13a9cafd73cf5437c1/kv/test_raftstore/test_test.go#L598-L609

I have questions about PeerId and StoreId in TestBasicConfChange3B. 

Line 601 creates a Peer with PeerId 4, StoreId 2.

Question 1: Why different Ids are needed here? I searched the code and find all calls to `NewPeer` has 2 equivalent arguments. I doubt it's a typo here.

Question 2: According to the current situation, I suppose the newly created Peer 4 will use `cluster.engines[2]`. However, I logged `peerMsgHandler.peerStorage.Engines` and `cluster.engines[i]`, finding that `engines` of Peer 4 has the same address as `cluster.engines[4]`. It means that Peer 4 was created with `cluster.engines[2]`, not `cluster.engines[4]`. Is this expected? If not, and it's because of my code, can you kindly provide me some hints about what could be wrong?

**Comment by NingLin-P** [comment]
> Question 1: Why different Ids are needed here? I searched the code and find all calls to NewPeer has 2 equivalent arguments. I doubt it's a typo here.

It is not a typo, the 2 arguments to `NewPeer` are not necessarily equivalent, but the `PeerId` should be unique. Because 1, 2 and 3 were used, so we use 4 as the next `PeerId` here.

> Question 2: According to the current situation, I suppose the newly created Peer 4 will use cluster.engines[2]. However, I logged peerMsgHandler.peerStorage.Engines and cluster.engines[i], finding that engines of Peer 4 has the same address as cluster.engines[4]. It means that Peer 4 was created with cluster.engines[2], not cluster.engines[4]. Is this expected? 

Do you mean Peer 4 uses `cluster.engines[4]`? I think it is not expected, `cluster.engines` is index by `StoreId`, so Peer 4 should use `cluster.engines[2]` as its `StoreId` is 2.
