### ISSUE TITLE
Potential race condition?

### ISSUE THREAD

**Issue by yujqiao** [talent-plan/tinykv#252]
https://github.com/tidb-incubator/tinykv/blob/aa616ee4049a41b3804b5160798521d674e90cc1/kv/test_raftstore/cluster.go#L182-L201

L185 finds a region by the key and L188 commands the leader of that region to act with the key. If a split happens between L185 and L188, the leader may not find the key in its region. Normally it's not an issue because the leader should check if the key is in that region when proposing the command or committing that entry. If not, it just replies with an error and the loop in `func Request` continues.

But if the command doesn't contain a key for the leader to check, for example, when given a snap command, the leader just commits and reply success, even if the leader is not responsible for that key.

And this happens with the code below

https://github.com/tidb-incubator/tinykv/blob/aa616ee4049a41b3804b5160798521d674e90cc1/kv/test_raftstore/cluster.go#L357-L374

It seems that this snippet intends to scan the region responsible for the given key. L372 trys to get the region responsible for the key. Unfortunately, that may not be the correct region due to the race condition described above.

*I've not understood how these test work thoroughly. I may be wrong :)*

**Comment by NingLin-P** [comment]
Sorry for the delay! When sending a request we also attach the `RegionEpoch` with it
https://github.com/tidb-incubator/tinykv/blob/aa616ee4049a41b3804b5160798521d674e90cc1/kv/test_raftstore/cluster.go#L187

`RegionEpoch.version` should be increased when a region's key range is changed, so we can use `RegionEpoch.version` to check if the region's key range is matching the requested one when we need to, for example:
https://github.com/tidb-incubator/tinykv/blob/aa616ee4049a41b3804b5160798521d674e90cc1/kv/raftstore/peer_msg_handler.go#L95
