### ISSUE TITLE
Question about handling KvPrewrite and KvCommit

### ISSUE THREAD

**Issue by ywave620** [talent-plan/tinykv#256]
I had read this post https://pingcap.com/blog-cn/tikv-source-code-reading and this https://pingcap.com/blog-cn/tikv-source-code-reading-11/, they suggest that TiKV will 
1. latch every key in the KvPrewrite/KvCommit 
2. call RaftKV.async_snapshot() (i.e. propose a RaftSnapCmd) to get a snapshot of the state machine
3. when the RaftSnapCmd is applied, read the keys from the snapshot and call the callback passed to RaftKV.async_snapshot()
4. call RaftKV.async_write() (i.e. propose a RaftWriteCmd) to write the keys

From the comment in https://github.com/tidb-incubator/tinykv/blob/course/kv/transaction/latches/latches.go, I can tell this is also the recommended way to implement KvPrewrite and KvCommit in TinyKV.

Here is the question: Instead of dividing the procedure into two phases(read and write), why not use a single raft command and leverage badger.Txn, like this:
1. propose a RaftPrewriteCmd
2. when the RaftPrewriteCmd is applied, start a badger.Txn and do the read and write in the Txn

In this way, we don't need latch any more and we cut half of the traffic.

**Comment by NingLin-P** [comment]
We need latch tracking inflight writes which still replicating under raft and can't read from badger yet.

**Comment by ywave620** [comment]
> We need latch tracking inflight writes which still replicating under raft and can't read from badger yet.

Thanks for comment, here is my point:
- The reason why TiKV uses latch is that it uses 2 raft commands to perform a KvPrewrite/KvCommit and it needs to enforce the atomicity of them.
- If we only use one raft command, then we get atomicity directly(without latches) because we can apply this raft command in a badger.Txn which provides ACID feature.

**Comment by NingLin-P** [comment]
We can't do that because a distributed transaction can invoke multiple regions.

**Comment by ywave620** [comment]
I don't quite understand what you said, could you show more details?

Here is my best explantion. 
- Pecolator paper uses a row(key) transaction, which provides atomic read-modify-write transaction on individual rows(keys). 
- According to the paper, we don't need a transaction against multiple keys, we only need a transaction against a single key and do it multiple times(and if any of them fail, then abort, otherwise commit).
- Prewrite mentioned in the paper contains one key.
- A KvPrewrite request in TiKV may contain more than one key(all in the same region), TiKV will process them once instead of processing them one by one, that‘s ok(and better).
- `process them once` refers to the approach in my original comment(i.e. a single RaftPrewriteCmd and leverage a badger.Txn)
- If there are multiple regions involved in a distributed transaction, then multiple KvPrewrite will be sent to different leaders, that's okay, again, we don't need to read-modify-write all the keys in a large, universal transaction.

**Comment by Connor1996** [comment]
> I had read this post https://pingcap.com/blog-cn/tikv-source-code-reading and this https://pingcap.com/blog-cn/tikv-source-code-reading-11/, they suggest that TiKV will
> 
> 1. latch every key in the KvPrewrite/KvCommit
> 2. call RaftKV.async_snapshot() (i.e. propose a RaftSnapCmd) to get a snapshot of the state machine
> 3. when the RaftSnapCmd is applied, read the keys from the snapshot and call the callback passed to RaftKV.async_snapshot()
> 4. call RaftKV.async_write() (i.e. propose a RaftWriteCmd) to write the keys
> 
> From the comment in https://github.com/tidb-incubator/tinykv/blob/course/kv/transaction/latches/latches.go, I can tell this is also the recommended way to implement KvPrewrite and KvCommit in TinyKV.
> 
> Here is the question: Instead of dividing the procedure into two phases(read and write), why not use a single raft command and leverage badger.Txn, like this:
> 
> 1. propose a RaftPrewriteCmd
> 2. when the RaftPrewriteCmd is applied, start a badger.Txn and do the read and write in the Txn
> 
> In this way, we don't need latch any more and we cut half of the traffic.

You're right. The essential of the latch is to provide row-based transaction. We can simply leverage the `badger.Txn` to do that. But due to TiKV is implemented in that way, TinyKV just follows the design.

**Comment by NingLin-P** [comment]
Oh sorry, I misunderstood your proposal as using one command for both KvPrewrite and KvCommit. Indeed, using one raft command to perform read and write for KvPrewrite/KvCommit when it is applied can archive AICD, but IMO:
- according to the raft thesis 6.4, we don't need to propose a raft log to get a snapshot of the state machine
- latch can also help write conflict, with latch we can reject conflict writes before it is proposed to raft instead of when it is gonna apply, and avoiding to replicate it

**Comment by ywave620** [comment]
> Oh sorry, I misunderstood your proposal as using one command for both KvPrewrite and KvCommit. Indeed, using one raft command to perform read and write for KvPrewrite/KvCommit when it is applied can archive AICD, but IMO:
> 
> * according to the raft thesis 6.4, we don't need to propose a raft log to get a snapshot of the state machine
> * latch can also help write conflict, with latch we can reject conflict writes before it is proposed to raft instead of when it is gonna apply, and avoiding to replicate it

OK, I got your idea👍
