### ISSUE TITLE
No term in TestLeaderCycle2AA in  raft_test.go

### ISSUE THREAD

**Issue by mobilephone724** [talent-plan/tinykv#257]
In this test, when the "campaignerID" sending "pb.MessageType_MsgHup" to itself, term information isn't specified. When I specify the term information, the test is passed but not passed when I don't specify it. Should the term be expected not to specified?

**Comment by NingLin-P** [comment]
If the term information doesn't specify, it will be the default value **0**, please check if your implement handle this case well
