### ISSUE TITLE
How to run TinyKV cluster?

### ISSUE THREAD

**Issue by Cherrison** [talent-plan/tinykv#261]
The Readme said, need tinykv-scheduer and tinykv-server build by this project, also need tinysql, But where is the that???

The tinysql course build that?, **But If am only do this tinykv project**, how can I run these?

And also a question, in the Readme that run one kv, one sql and one scheduer how can I run a tinykv cluster?[tidb can use tiup but how to run this project tinykv as a cluster?]

**Comment by Connor1996** [comment]
1. You need to finish the implementation of tinysql to build a binary. 

2. If you don't want to do the tinysql project, I can provide a complete tinysql binary when you finish the implementation of tinykv.

3. run the tinykv with additional args `--schedulerAddr=<tinyscheduler_addr> --storeAddr=<tinykv_binding_addr>`. See https://github.com/tidb-incubator/tinykv/blob/course/kv/main.go#L25
