### ISSUE TITLE
memory leak in 2b tests

### ISSUE THREAD

**Issue by byte-drift** [talent-plan/tinykv#264]
I found around 3GB memory leak every time I run 2b tests.
And when I run all 2b tests like "go test -run 2B", it will start all 11 tests one by one. Finally memory leak will get to tens of GiB and process will be killed.
Even if I just start the cluster and shut it down immediately, it will result to about 2GB memory leak.
![image](https://user-images.githubusercontent.com/30173268/125198964-bf74b280-e296-11eb-8b9f-135fd8efaf62.png)
Seems problems happen in badger, not my own code...

**Comment by Connor1996** [comment]
Do you use the latest commit? Seems same as https://github.com/tidb-incubator/tinykv/issues/238

**Comment by byte-drift** [comment]
> Do you use the latest commit? Seems same as #238

I do use the latest commit. I started the talent plan one month ago, but #238 is issued on Jan..

**Comment by Connor1996** [comment]
You can follow the way of the issue to check. 2GB memory maybe not a leak, it just due to badger's cache and golang runtime doesn't return the memory back to system in time.
