### ISSUE TITLE
`TestOneSplit3B` progress may be much slower when leader is 5 before partition [1,2,3,4] [5]

### ISSUE THREAD

**Issue by unconsolable** [talent-plan/tinykv#266]
In `TestOneSplit3B`, I find that facing the partition [1,2,3,4] [5], the test progress is much slower when the leader before partition is 5 .  
I read `cluster.go` roughly and find that the cluster determines the leader via the heartbeat from leader peer, however under network partition, [1, 2, 3, 4] will elect a new leader, thus there are two leader sending region heartbeats to scheduler. But it looks like `MockSchedulerClient` don't distinguish these region heartbeats, it just set leader via the latest heartbeat.
```go
func (m *MockSchedulerClient) RegionHeartbeat(req *schedulerpb.RegionHeartbeatRequest) error {
        ......
	regionID := req.Region.GetId()
	for _, p := range req.Region.GetPeers() {
		delete(m.pendingPeers, p.GetId())
	}
	for _, p := range req.GetPendingPeers() {
		m.pendingPeers[p.GetId()] = p
	}
	m.leaders[regionID] = req.Leader
        ......
}
```
So when the stale leader send the most recent heartbeat to scheduler before the cluster propose a command, the cluster will propose  command on the stale leader for a while, then it will switch to another peer, thus the progress is much slower.
I wonder this issue is related to my implementation or test framework. Maybe a possible workaround is to transfer leader to another when the leader is 5.

**Comment by Connor1996** [comment]
It's expected cause it's hard to distinguish which one is the available leader.

**Comment by unconsolable** [comment]
Got it, thank you.
