### ISSUE TITLE
Use as less dependencies as possible

### ISSUE THREAD

**Issue by tisonkun** [talent-plan/tinykv#268]
As a training course, we don't have to use dependencies like

* github.com/pingcap/check
* github.com/pingcap/log
* github.com/pingcap-incubator/tinykv/log

... also, we use three errors packages (juju, pingcap, pkg), which increase the understanding difficulty.

**Comment by Connor1996** [comment]
Agree🙋‍♂️

**Comment by tisonkun** [comment]
Closed as no more activities.
