### ISSUE TITLE
What changes Connor1996/badger on the top of upstream?

### ISSUE THREAD

**Issue by tisonkun** [talent-plan/tinykv#269]
We don't use either https://github.com/pingcap/badger or https://github.com/dgraph-io/badger but a fork

```
github.com/Connor1996/badger v1.5.1-0.20210202034640-5ff470f827f8
```

why?

**Comment by Connor1996** [comment]
Add the support of `Ingest` of `badger`. And for `pingcap/badger`, the `Ingest` is a little bit complex, so using a fork which is an old version of `pingcap/badger` with some fixes.

**Comment by tisonkun** [comment]
Closed as information delivered.
