### ISSUE TITLE
Rearrange code of project1

### ISSUE THREAD

**Issue by tisonkun** [talent-plan/tinykv#283]

**Comment by pupillord** [comment]
I have two ideas on how to rearrange the code of different projects:
1. Create a folder for each project, for example:
─ project1
└── project1a
└── project1b
─ project2
└── project2a
└── project2b

2. Keep the current directory structure, subdivide the files and add suffixes, for example:
─ server
└── server_ pro1
└── server_ pro2a
└── server_ pro2b

How about these two ideas?  Or is there another batter way?

**Comment by tisonkun** [comment]
I'd prefer the second way and let's see whether we have a better name to reflect the code instead of `pro1` `pro2a`.

It should be that the project depends on files provided instead of files affected by the project.

**Comment by tisonkun** [comment]
For example, we don't have to push everything under `server.go`, but

Project 1: raw_api,go

Project 4: txn_api.go

and keep common part in server.go with a little comment as in `Server` document field usage.

**Comment by tisonkun** [comment]
Closed as partially done and no more activities.
