### ISSUE TITLE
project2b panic on test code (find no region for 30203030303030)

### ISSUE THREAD

**Issue by xishuaidelin** [talent-plan/tinykv#284]
when I test the 2b I find that the code panic before coming in my code. I find that the cluster can't get the region from the given key. in test_test.go:226, this line will call (*Cluster).MustPut which then will call (*Cluster).GetRegion, and then call the schedulerclient.Getregion. but the schedulerclient.regionsRange.root is nil then return nil which would cause a panic. anyone also encounter this?

**Comment by unconsolable** [comment]
Please check #241 , looks like the errors are quite similar.

I remembered that I had encounter the same issues when I was testing project2b, and I solved it according the solution given in this issue.

**Comment by unconsolable** [comment]
Please check #241 , looks like the errors are quite similar.

I remembered that I had encountered the same issues when I was testing project2b, and I solved it according the solution given in this issue.

**Comment by xishuaidelin** [comment]
> Please check #241 , looks like the errors are quite similar.
> 
> I remembered that I had encountered the same issues when I was testing project2b, and I solved it according the solution given in this issue.

see it! thanks!!
