### ISSUE TITLE
Project2 test case

### ISSUE THREAD

**Issue by sunshinejiali** [talent-plan/tinykv#297]
In project2a's test case, a node may have log entries that are newer than its own current term, which does not follow the logic in Raft.

**Comment by Connor1996** [comment]
which test case?

**Comment by sunshinejiali** [comment]
Sorry. For example, tests[0] in the TestFollowerAppendEntries2AB test case.

The following code has 

`r.Step(pb.Message{From: 2, To: 1, MsgType: pb.MessageType_MsgAppend, Term: 2, LogTerm: tt.term, Index: tt.index, Entries: tt.ents}).`

According to the test case, LogTerm: tt.term==3, but Term==2, is this reasonable?

**Comment by Connor1996** [comment]
PTAL @NingLin-P

**Comment by NingLin-P** [comment]
Sorry for missing the message, and thanks for opening this issue @sunshinejiali , it may fix by https://github.com/tidb-incubator/tinykv/pull/299

**Comment by sunshinejiali** [comment]
Well, thank you~
