### ISSUE TITLE
make proto error

### ISSUE THREAD

**Issue by sunshinejiali** [talent-plan/tinykv#303]
When running `make proto` to generate `*.proto.go`, the following error occurs. I suspect that the repository in `proto/tools.json` is invalid. How can I fix it?

![image](https://user-images.githubusercontent.com/56687539/141415676-954d6592-bcd9-40c7-8220-cd16a87696a8.png)

``` json
{
    "Tools": [
      //....
      {
        "Repository": "golang.org/x/tools/cmd/goimports",
        "Commit": "04b5d21e00f1f47bd824a6ade581e7189bacde87"
      }
    ],
  }
```

**Comment by huaouo** [comment]
Looks like a network issue. Have you tried to set `GOPROXY="https://goproxy.io,direct"`?

**Comment by sunshinejiali** [comment]
I also thought it was a proxy problem before, but it doesn't seem to be. 

Do your `make proto` execute correctly?
