### ISSUE TITLE
报名时间错过了, 可以补报么

### ISSUE THREAD

**Issue by 42thcoder** [talent-plan/tinykv#307]
https://m.creatby.com/v2/manage/book/oa4occ/?from=singlemessage&pageid=page_f4fd8b73071e8ddd#page/page_f4fd8b73071e8ddd

找不到沟通的渠道, 如果打扰了, 请原谅

**Comment by zhangyangyu** [comment]
本期报名已经结束了，请期待下期，谢谢。
