### ISSUE TITLE
improve test case of lab2aa

### ISSUE THREAD

**Issue by O1iveira7** [talent-plan/tinykv#315]
function testNonleaderStartElection in _raft/raft_paper_test.go_ seems to assume that electionTimeout is a constant number
```go
func testNonleaderStartElection(t *testing.T, state StateType) {
	// election timeout
	et := 10
        ...
	for i := 1; i < 2*et; i++ {
		r.tick()
	}
        ...
}
```
but TestFollowerElectionTimeoutRandomized2AA requires that electionTimeout is a randomized number.
So in some cases I can't pass these two tests simultaneously.

**Comment by rien7** [comment]
```go
func testNonleaderStartElection(t *testing.T, state StateType) {
	// election timeout
	et := 10
        r := newTestRaft(1, []uint64{1, 2, 3}, et, 1, NewMemoryStorage())
        ...
}
```
The variable `et` is used to init the `electionTimeout` in `Raft`, which does not mean that `electionTimeout` can not be changed at the time of a new election.
So you can randomise adjust the `electionTimeout` at the start of a new election to ensure that split votes are rare.
