### ISSUE TITLE
Confusion about election

### ISSUE THREAD

**Issue by xingdiyou** [talent-plan/tinykv#327]
Why does candidate need to become follower after election failure?
```
func TestLeaderElectionOverwriteNewerLogs2AB(t *testing.T) {
	cfg := func(c *Config) {
		c.peers = idsBySize(5)
	}
	// This network represents the results of the following sequence of
	// events:
	// - Node 1 won the election in term 1.
	// - Node 1 replicated a log entry to node 2 but died before sending
	//   it to other nodes.
	// - Node 3 won the second election in term 2.
	// - Node 3 wrote an entry to its logs but died without sending it
	//   to any other nodes.
	//
	// At this point, nodes 1, 2, and 3 all have uncommitted entries in
	// their logs and could win an election at term 3. The winner's log
	// entry overwrites the losers'. (TestLeaderSyncFollowerLog tests
	// the case where older log entries are overwritten, so this test
	// focuses on the case where the newer entries are lost).
	n := newNetworkWithConfig(cfg,
		entsWithConfig(cfg, 1),     // Node 1: Won first election
		entsWithConfig(cfg, 1),     // Node 2: Got logs from node 1
		entsWithConfig(cfg, 2),     // Node 3: Won second election
		votedWithConfig(cfg, 3, 2), // Node 4: Voted but didn't get logs
		votedWithConfig(cfg, 3, 2)) // Node 5: Voted but didn't get logs

	// Node 1 campaigns. The election fails because a quorum of nodes
	// know about the election that already happened at term 2. Node 1's
	// term is pushed ahead to 2.
	n.send(pb.Message{From: 1, To: 1, MsgType: pb.MessageType_MsgHup})
	sm1 := n.peers[1].(*Raft)
	if sm1.State != StateFollower {
		t.Errorf("state = %s, want StateFollower", sm1.State)
	}
	if sm1.Term != 2 {
		t.Errorf("term = %d, want 2", sm1.Term)
	}

	// Node 1 campaigns again with a higher term. This time it succeeds.
	n.send(pb.Message{From: 1, To: 1, MsgType: pb.MessageType_MsgHup})
	if sm1.State != StateLeader {
		t.Errorf("state = %s, want StateLeader", sm1.State)
	}
	if sm1.Term != 3 {
		t.Errorf("term = %d, want 3", sm1.Term)
	}

	// Now all nodes agree on a log entry with term 1 at index 1 (and
	// term 3 at index 2).
	for i := range n.peers {
		sm := n.peers[i].(*Raft)
		entries := sm.RaftLog.entries
		if len(entries) != 2 {
			t.Fatalf("node %d: len(entries) == %d, want 2", i, len(entries))
		}
		if entries[0].Term != 1 {
			t.Errorf("node %d: term at index 1 == %d, want 1", i, entries[0].Term)
		}
		if entries[1].Term != 3 {
			t.Errorf("node %d: term at index 2 == %d, want 3", i, entries[1].Term)
		}
	}
}
```

**Comment by rien7** [comment]
If the majority of nodes agree the candidate, than the candidate will turn to Leader State. But if the **majority** of nodes reject the candidate's VoteRequest, it means this candidate can't be Leader **in this term**, and maybe other node will be Leader. So it should turn to Follower State.

There are three reasons cause this case (majority of nodes reject) in detail:

1. the candidate's term is out of date, so the other nodes reject it. in this case, the candidate should turn back to Follower. 
2. the majority of nodes have voted for other node in this term, which means a leader has been selected, so the candidate should turn to Follower State. 
3. the candidate's log is shorter than the majority of nodes. In this situation the candidate can't be voted to be Leader, so it should be Follower

**Comment by xingdiyou** [comment]
> If the majority of nodes agree the candidate, than the candidate will turn to Leader State. But if the **majority** of nodes reject the candidate's VoteRequest, it means this candidate can't be Leader **in this term**, and maybe other node will be Leader. So it should turn to Follower State.
> 
> There are three reasons cause this case (majority of nodes reject) in detail:
> 
> 1. the candidate's term is out of date, so the other nodes reject it. in this case, the candidate should turn back to Follower.
> 2. the majority of nodes have voted for other node in this term, which means a leader has been selected, so the candidate should turn to Follower State.
> 3. the candidate's log is shorter than the majority of nodes. In this situation the candidate can't be voted to be Leader, so it should be Follower

I think it is a redundant conversion. According to raft paper in section 5.2, a candidate should continue in this state until one of three things happens: 
a) it wins the election
b) another server establishes itself as leader
c) a period of time goes by with no winner

**Comment by rien7** [comment]
> > If the majority of nodes agree the candidate, than the candidate will turn to Leader State. But if the **majority** of nodes reject the candidate's VoteRequest, it means this candidate can't be Leader **in this term**, and maybe other node will be Leader. So it should turn to Follower State.
> > There are three reasons cause this case (majority of nodes reject) in detail:
> > 
> > 1. the candidate's term is out of date, so the other nodes reject it. in this case, the candidate should turn back to Follower.
> > 2. the majority of nodes have voted for other node in this term, which means a leader has been selected, so the candidate should turn to Follower State.
> > 3. the candidate's log is shorter than the majority of nodes. In this situation the candidate can't be voted to be Leader, so it should be Follower
> 
> I think it is a redundant conversion. According to raft paper in section 5.2, a candidate should continue in this state until one of three things happens: a) it wins the election b) another server establishes itself as leader c) a period of time goes by with no winner

In fact, the three scenarios I mentioned above match up with 'Another server establishes itself as leader' because most of nodes reject this candidate, so it can't 'win the election' and it will not be 'split vote'(no winner).

The raft paper doesn't directly mention what the candidate will do in the event of an election defeat. Of course you can do nothing until it wins the election or receives a message from the leader, but I think this test case  points out what a candidate should do if it loses an election.

**Comment by xingdiyou** [comment]
> > > If the majority of nodes agree the candidate, than the candidate will turn to Leader State. But if the **majority** of nodes reject the candidate's VoteRequest, it means this candidate can't be Leader **in this term**, and maybe other node will be Leader. So it should turn to Follower State.
> > > There are three reasons cause this case (majority of nodes reject) in detail:
> > > 
> > > 1. the candidate's term is out of date, so the other nodes reject it. in this case, the candidate should turn back to Follower.
> > > 2. the majority of nodes have voted for other node in this term, which means a leader has been selected, so the candidate should turn to Follower State.
> > > 3. the candidate's log is shorter than the majority of nodes. In this situation the candidate can't be voted to be Leader, so it should be Follower
> > 
> > 
> > I think it is a redundant conversion. According to raft paper in section 5.2, a candidate should continue in this state until one of three things happens: a) it wins the election b) another server establishes itself as leader c) a period of time goes by with no winner
> 
> In fact, the three scenarios I mentioned above match up with 'Another server establishes itself as leader' because most of nodes reject this candidate, so it can't 'win the election' and it will not be 'split vote'(no winner).
> 
> The raft paper doesn't directly mention what the candidate will do in the event of an election defeat. Of course you can do nothing until it wins the election or receives a message from the leader, but I think this test case points out what a candidate should do if it loses an election.

Suppose there are 5 follower servers with duplicate log entries.
S1: term = 1 voteFor 1
S2: term = 1 voteFor 2
S3: term = 1 voteFor 3
S4: term = 1 voteFor 2
S5: term = 1 voteFor 3
If S1 requests other servers to vote, it will receive rejects from most of servers. However, no server establish itself as leader.

**Comment by rien7** [comment]
> > > > If the majority of nodes agree the candidate, than the candidate will turn to Leader State. But if the **majority** of nodes reject the candidate's VoteRequest, it means this candidate can't be Leader **in this term**, and maybe other node will be Leader. So it should turn to Follower State.
> > > > There are three reasons cause this case (majority of nodes reject) in detail:
> > > > 
> > > > 1. the candidate's term is out of date, so the other nodes reject it. in this case, the candidate should turn back to Follower.
> > > > 2. the majority of nodes have voted for other node in this term, which means a leader has been selected, so the candidate should turn to Follower State.
> > > > 3. the candidate's log is shorter than the majority of nodes. In this situation the candidate can't be voted to be Leader, so it should be Follower
> > > 
> > > 
> > > I think it is a redundant conversion. According to raft paper in section 5.2, a candidate should continue in this state until one of three things happens: a) it wins the election b) another server establishes itself as leader c) a period of time goes by with no winner
> > 
> > 
> > In fact, the three scenarios I mentioned above match up with 'Another server establishes itself as leader' because most of nodes reject this candidate, so it can't 'win the election' and it will not be 'split vote'(no winner).
> > The raft paper doesn't directly mention what the candidate will do in the event of an election defeat. Of course you can do nothing until it wins the election or receives a message from the leader, but I think this test case points out what a candidate should do if it loses an election.
> 
> Suppose there are 5 follower servers with duplicate log entries. S1: term = 1 voteFor 1 S2: term = 1 voteFor 2 S3: term = 1 voteFor 3 S4: term = 1 voteFor 2 S5: term = 1 voteFor 3 If S1 requests other servers to vote, it will receive rejects from most of servers. However, no server establish itself as leader.

"Vote for itself" in raft paper means `votes[r.id] = true` in this code, and the `Vote` field will only set to other server who send VoteRequest first, and it will not set to itself.

But you reminded me that "split vote" can indeed exist at `S1 voteFor 4`, which is my fault, and I apologise for my previous statement.
