### ISSUE TITLE
go1.17.2 runtime panic when running test

### ISSUE THREAD

**Issue by ghostant-1017** [talent-plan/tinykv#360]
It's ok when running on go1.13.10

**Comment by ghostant-1017** [comment]
GO111MODULE=on go test -v --count=1 --parallel=1 -p=1 ./kv/server -run 1 
=== RUN   TestRawGet1
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff700c570a]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff700c570a
stack: frame={sp:0x7ffeefbff698, fp:0x7ffeefbff6e8} stack=[0x7ffeefb80738,0x7ffeefbff7a0)
0x00007ffeefbff598:  0x01007ffeefbff5b8  0x0000000000000004 
0x00007ffeefbff5a8:  0x000000000000001f  0x00007fff700c570a 
0x00007ffeefbff5b8:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbff5c8:  0x0000000004037fb1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff668 
0x00007ffeefbff5d8:  0x0000000004927335  0x00007ffeefbff620 
0x00007ffeefbff5e8:  0x0000000004038268 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000000503d4c0 
0x00007ffeefbff5f8:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbff608:  0x00007ffeefbff668  0x0000000004037fb1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff618:  0x000000000503d4c0  0x00007ffeefbff658 
0x00007ffeefbff628:  0x00000000040381f0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff638 
0x00007ffeefbff638:  0x0000000004038220 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000000503d4c0 
0x00007ffeefbff648:  0x0000000004037fb1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff668 
0x00007ffeefbff658:  0x00007ffeefbff688  0x0000000004037fb1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff668:  0x00007ffeefbff670  0x0000000004037fe0 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbff678:  0x0000000004934470  0x000000000000002a 
0x00007ffeefbff688:  0x00007ffeefbff6d8  0x000000000404e436 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbff698: <0x0000000004934470  0x0000000004d906b0 
0x00007ffeefbff6a8:  0x0100000004f24aa0  0x0000000005753e40 
0x00007ffeefbff6b8:  0x0000000000001800  0x000000000503d660 
0x00007ffeefbff6c8:  0x0000000005753eb8  0x00007ffeefbff728 
0x00007ffeefbff6d8:  0x00007ffeefbff720 !0x00007fff700c570a 
0x00007ffeefbff6e8: >0x00007ffeefbff720  0x0000000004f10000 
0x00007ffeefbff6f8:  0x00000000000004bd  0x0000000004152605 <golang.org/x/sys/unix.libc_flock_trampoline+0x0000000000000005> 
0x00007ffeefbff708:  0x000000000406d03f <runtime.syscall+0x000000000000001f>  0x000000c0001a1460 
0x00007ffeefbff718:  0x0000000005791198  0x000000c0001a1430 
0x00007ffeefbff728:  0x000000000406ae90 <runtime.asmcgocall+0x0000000000000070>  0x000000000401b755 <runtime.SetFinalizer.func2+0x0000000000000035> 
0x00007ffeefbff738:  0x000000c00018d800  0x0000000004961ec0 
0x00007ffeefbff748:  0x0000000000000010  0x000000000481f6e0 
0x00007ffeefbff758:  0x0000000000000bf8  0x000000c00018f040 
0x00007ffeefbff768:  0x0000000004068fa9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbff778:  0x0000000004a03ee0  0x000000000503d4c0 
0x00007ffeefbff788:  0x00007ffeefbff7d8  0x0000000004068ea5 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbff798:  0x0000000004068e5d <runtime.rt0_go+0x000000000000013d> 
runtime.throw({0x4934470, 0x4d906b0})
        /usr/local/go1.17.2/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff700c570a
stack: frame={sp:0x7ffeefbff698, fp:0x7ffeefbff6e8} stack=[0x7ffeefb80738,0x7ffeefbff7a0)
0x00007ffeefbff598:  0x01007ffeefbff5b8  0x0000000000000004 
0x00007ffeefbff5a8:  0x000000000000001f  0x00007fff700c570a 
0x00007ffeefbff5b8:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbff5c8:  0x0000000004037fb1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff668 
0x00007ffeefbff5d8:  0x0000000004927335  0x00007ffeefbff620 
0x00007ffeefbff5e8:  0x0000000004038268 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000000503d4c0 
0x00007ffeefbff5f8:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbff608:  0x00007ffeefbff668  0x0000000004037fb1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff618:  0x000000000503d4c0  0x00007ffeefbff658 
0x00007ffeefbff628:  0x00000000040381f0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff638 
0x00007ffeefbff638:  0x0000000004038220 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000000503d4c0 
0x00007ffeefbff648:  0x0000000004037fb1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff668 
0x00007ffeefbff658:  0x00007ffeefbff688  0x0000000004037fb1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff668:  0x00007ffeefbff670  0x0000000004037fe0 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbff678:  0x0000000004934470  0x000000000000002a 
0x00007ffeefbff688:  0x00007ffeefbff6d8  0x000000000404e436 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbff698: <0x0000000004934470  0x0000000004d906b0 
0x00007ffeefbff6a8:  0x0100000004f24aa0  0x0000000005753e40 
0x00007ffeefbff6b8:  0x0000000000001800  0x000000000503d660 
0x00007ffeefbff6c8:  0x0000000005753eb8  0x00007ffeefbff728 
0x00007ffeefbff6d8:  0x00007ffeefbff720 !0x00007fff700c570a 
0x00007ffeefbff6e8: >0x00007ffeefbff720  0x0000000004f10000 
0x00007ffeefbff6f8:  0x00000000000004bd  0x0000000004152605 <golang.org/x/sys/unix.libc_flock_trampoline+0x0000000000000005> 
0x00007ffeefbff708:  0x000000000406d03f <runtime.syscall+0x000000000000001f>  0x000000c0001a1460 
0x00007ffeefbff718:  0x0000000005791198  0x000000c0001a1430 
0x00007ffeefbff728:  0x000000000406ae90 <runtime.asmcgocall+0x0000000000000070>  0x000000000401b755 <runtime.SetFinalizer.func2+0x0000000000000035> 
0x00007ffeefbff738:  0x000000c00018d800  0x0000000004961ec0 
0x00007ffeefbff748:  0x0000000000000010  0x000000000481f6e0 
0x00007ffeefbff758:  0x0000000000000bf8  0x000000c00018f040 
0x00007ffeefbff768:  0x0000000004068fa9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbff778:  0x0000000004a03ee0  0x000000000503d4c0 
0x00007ffeefbff788:  0x00007ffeefbff7d8  0x0000000004068ea5 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbff798:  0x0000000004068e5d <runtime.rt0_go+0x000000000000013d> 
runtime.sigpanic()
        /usr/local/go1.17.2/src/runtime/signal_unix.go:719 +0x396

goroutine 27 [syscall]:
syscall.syscall(0x4152600, 0x6, 0x6, 0x0)
        /usr/local/go1.17.2/src/runtime/sys_darwin.go:22 +0x3b fp=0xc0001a1460 sp=0xc0001a1440 pc=0x4067adb
syscall.syscall(0xc0000784c8, 0x0, 0xc000000000, 0x13)
        <autogenerated>:1 +0x26 fp=0xc0001a14a8 sp=0xc0001a1460 pc=0x406d886
golang.org/x/sys/unix.Flock(0xc000360c70, 0xe)
        /Users/cyan/go/pkg/mod/golang.org/x/sys@v0.0.0-20191120155948-bd437916bb0e/unix/zsyscall_darwin_amd64.go:1150 +0x38 fp=0xc0001a14d8 sp=0xc0001a14a8 pc=0x4152258
github.com/Connor1996/badger.acquireDirectoryLock({0xc000360c70, 0xe}, {0x4908965, 0x4010c4e}, 0x0)
        /Users/cyan/go/pkg/mod/github.com/!connor1996/badger@v1.5.1-0.20200306031920-9bbcbd8ba570/dir_unix.go:61 +0x125 fp=0xc0001a1598 sp=0xc0001a14d8 pc=0x43a3045
github.com/Connor1996/badger.Open({{0xc000360c70, 0xe}, {0xc000360c70, 0xe}, 0x1, 0x1, 0x0, 0x4000000, 0x20, 0x5, ...})
        /Users/cyan/go/pkg/mod/github.com/!connor1996/badger@v1.5.1-0.20200306031920-9bbcbd8ba570/db.go:212 +0x3c5 fp=0xc0001a1a70 sp=0xc0001a1598 pc=0x439c565
github.com/pingcap-incubator/tinykv/kv/util/engine_util.CreateDB({0x49081ed, 0x2}, 0xc000078eb8)
        /Users/cyan/Work/tmp/tinykv/kv/util/engine_util/engines.go:77 +0x1b8 fp=0xc0001a1d10 sp=0xc0001a1a70 pc=0x43c0b78
github.com/pingcap-incubator/tinykv/kv/storage/standalone_storage.NewStandAloneStorage(...)
        /Users/cyan/Work/tmp/tinykv/kv/storage/standalone_storage/standalone_storage.go:22
github.com/pingcap-incubator/tinykv/kv/server.TestRawGet1(0x40087f9)
        /Users/cyan/Work/tmp/tinykv/kv/server/server_test.go:52 +0x145 fp=0xc0001a1f70 sp=0xc0001a1d10 pc=0x46cd465
testing.tRunner(0xc00037e000, 0x4961558)
        /usr/local/go1.17.2/src/testing/testing.go:1259 +0x102 fp=0xc0001a1fc0 sp=0xc0001a1f70 pc=0x4107bc2
testing.(*T).Run·dwrap·21()
        /usr/local/go1.17.2/src/testing/testing.go:1306 +0x2a fp=0xc0001a1fe0 sp=0xc0001a1fc0 pc=0x41088ca
runtime.goexit()
        /usr/local/go1.17.2/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0001a1fe8 sp=0xc0001a1fe0 pc=0x406b181
created by testing.(*T).Run
        /usr/local/go1.17.2/src/testing/testing.go:1306 +0x35a

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000255d40, {0x4910ac6, 0x2ede27623ac}, 0x4961558)
        /usr/local/go1.17.2/src/testing/testing.go:1307 +0x375
testing.runTests.func1(0xc00036e6f0)
        /usr/local/go1.17.2/src/testing/testing.go:1598 +0x6e
testing.tRunner(0xc000255d40, 0xc0002a3d18)
        /usr/local/go1.17.2/src/testing/testing.go:1259 +0x102
testing.runTests(0xc0001f4800, {0x50108e0, 0xa, 0xa}, {0x408a1cd, 0x49143b6, 0x503cb40})
        /usr/local/go1.17.2/src/testing/testing.go:1596 +0x43f
testing.(*M).Run(0xc0001f4800)
        /usr/local/go1.17.2/src/testing/testing.go:1504 +0x51d
main.main()
        _testmain.go:61 +0x14b
FAIL    github.com/pingcap-incubator/tinykv/kv/server   0.670s
FAIL
make: *** [project1] Error 1

**Comment by buchuitoudegou** [comment]
I've got the same error when running with go1.17. Are there any solution except downgrading the go version?

**Comment by Connor1996** [comment]
Seem it's related with https://github.com/golang/go/issues/47776 indicating need to update `x/sys/unix`, would you like have a try? @buchuitoudegou

**Comment by buchuitoudegou** [comment]
> golang/go#47776

Thanks for your help @Connor1996 ! I'll try it later.

**Comment by buchuitoudegou** [comment]
> Seem it's related with https://github.com/golang/go/issues/47776 indicating need to update x/sys/unix, would you like have a try?

I've resolved it by upgrading the `sys` package:
```shell
go get golang.org/x/sys@latest
```
but upgrading the `sys` package may possibly cause compiling `github.com/shirou/gopsutil/disk` failed. Try to upgrade this package too:
```shell
go get github.com/shirou/gopsutil/disk@latest
```

**Comment by Connor1996** [comment]
@buchuitoudegou Would you like to file a PR to fix it (maybe need to upgrade it in `Connor1996/badger` first)?

**Comment by buchuitoudegou** [comment]
> @buchuitoudegou Would you like to file a PR to fix it (maybe need to upgrade it in `Connor1996/badger` first)?

Sure. I'll upgrade the `sys` package in `Connor1996/badger` first (It seems this package is used by badgerDB).

**Comment by Connor1996** [comment]
The PR in badger is merged @buchuitoudegou Please file an PR to update the badger

**Comment by buchuitoudegou** [comment]
Sorry for being late. PTAL #380 @Connor1996
