### ISSUE TITLE
Test case 'TestHeartbeatUpdateCommit2AB' of project2AB may have problems

### ISSUE THREAD

**Issue by bobbai00** [talent-plan/tinykv#370]
Dear developers,

I am currently working on project2AB. As I passed all other test cases, I still can't pass `TestHeartbeatUpdateCommit2AB`(tinykv/raft/raft_test.go). I checked the error message and was confused about the answer,
```go
func TestHeartbeatUpdateCommit2AB(t *testing.T) {
	tests := []struct {
		failCnt    int
		successCnt int
	}{
		{1, 1},
		{5, 3},
		{5, 10},
	}
	for i, tt := range tests {
		// ....Some code, omitted for now
                // ....
		nt.recover()
		nt.ignore(pb.MessageType_MsgAppend)
                 
                 // the leader sm2 will send MsgHeartbeat to sm1 and sm3, 
                 // sm2's committed value is 3, while sm1's commited value is 1
		nt.send(pb.Message{From: 2, To: 2, MsgType: pb.MessageType_MsgBeat}) 
		if sm1.RaftLog.committed > 1 {
                         // here, I got: "#0: expected sm1 commit: 1, got: 3", 
                         // should sm1's committed be updated by leader's Heartbeat Message?
			t.Fatalf("#%d: expected sm1 commit: 1, got: %d", i, sm1.RaftLog.committed)
		}
	}
}
```
I think the committed value of `sm1` should be 3 because of the `MsgHeartbeat` from `sm2`. And I noticed that `nt.ignore(pb.MessageType_MsgAppend)` is executed, does it imply that `sm2` should send additional `MsgAppend` to followers after sending Heartbeat in order to synchronize the commited value with followers?

**Comment by Connor1996** [comment]
PTAL @NingLin-P

**Comment by NingLin-P** [comment]
Peer 1 has different logs from the current leader peer 2, e.g logs with same index but different term, thus peer 1 should not update its commit index to commit wrong logs.

**Comment by bobbai00** [comment]
> Peer 1 has different logs from the current leader peer 2, e.g logs with same index but different term, thus peer 1 should not update its commit index to commit wrong logs.

Got it, Thanks.
