### ISSUE TITLE
Invalid links in main README

### ISSUE THREAD

**Issue by lnikon** [talent-plan/tinykv#374]
The following links for the English version of the documents are invalid:

* TiKV, the design of data storage (English, Chinese) - https://en.pingcap.com/blog/2017-07-11-tidbinternal1
* PD, the design of scheduling (English, Chinese) - https://en.pingcap.com/blog/2017-07-20-tidbinternal3

**Comment by Connor1996** [comment]
Thanks for your feedback, Fixed in #376
