### ISSUE TITLE
The Problem about peerMsgHandler.destroyPeer

### ISSUE THREAD

**Issue by Panlisong** [talent-plan/tinykv#375]
In kv/raftstore/peer_msg_handler.go:385
```go
if  isInitialized && meta.regionRanges.Delete(&regionItem{region: d.Region()}) == nil {
```
consider the situation bellow:
1. cluster commit the add confChange, _p0_ is created by store _s0_, current storeMeta in _s0_ is: **regions: map[s0 : <...>] regionRanges: <region_id: s0, region_epoch: <>>**
2. peer  _p0_ was added into region but not receive snapshot(i.e. not initialized), so the storeMeta in _s0_ remains constant
3. cluster commit the remove confChange while the peer p0 have not receive the remove confChange entry
4. cluster remove p0 in router, so _p0_ will never receive message from leader
5. next time cluster commit add _p1_ in _s0_, since _p1_>_p0_(peer_id), when in peerMsgHandler.checkMessage:265, it will call peerMsgHandler.destroyPeer to destroy _p0_
5. at this time, since _p0_ is uninitialized, the if statement upon will be short circuit so the **meta.regionRanges.Delete()** will not execute, so the current storeMeta in _s0_ is: **regions: map[] regionRanges: <region_id: x, region_epoch: <>>**
6. after the destroy finished, peerMsgHandler will call 
```go
kv/raftstore/peer_msg_handler.go:266
d.ctx.router.sendStore(message.NewMsg(message.MsgTypeStoreRaftMessage, msg))
```
7. the store will try to create peer but will fail in this statement since _s0_ regionRanges contains: **<region_id: s0, region_epoch: <>>**
```go
kv/raftstore/store_worker.go:209
	for _, region := range meta.getOverlapRegions(&metapb.Region{
		StartKey: msg.StartKey,
		EndKey:   msg.EndKey,
	}) {
		log.Debugf("msg %s is overlapped with exist region %s", msg, region)
		if util.IsFirstVoteMessage(msg.Message) {
			meta.pendingVotes = append(meta.pendingVotes, msg)
		}
		return false, nil
	}
```

My solution:
reverse order to avoid short circuit
```go
kv/raftstore/peer_msg_handler.go:385
- if  isInitialized && meta.regionRanges.Delete(&regionItem{region: d.Region()}) == nil {
+ if  meta.regionRanges.Delete(&regionItem{region: d.Region()}) == nil && isInitialized {
```

**Comment by Connor1996** [comment]
the region info is inserted into `regionRanges` only after it is initialized.

**Comment by Panlisong** [comment]
thx
