### ISSUE TITLE
launch problem when startup './tinykv-server -path=data'

### ISSUE THREAD

**Issue by itboyljm** [talent-plan/tinykv#389]
$ ./tinykv-server -path=data
2022/04/19 12:12:39.376138 main.go:49: [info] Server started with conf &{StoreAddr:127.0.0.1:20160 Raft:true SchedulerAddr:127.0.0.1:2379 LogLevel:info DBPath:data RaftBaseTickInterval:1s RaftHeartbeatTicks:2 RaftElectionTimeoutTicks:10 RaftLogGCTickInterval:10s RaftLogGcCountLimit:128000 SplitRegionCheckTickInterval:10s SchedulerHeartbeatTickInterval:100ms SchedulerStoreHeartbeatTickInterval:10s RegionMaxSize:150994944 RegionSplitSize:100663296}
2022/04/19 12:12:39.464117 client.go:96: [info] [][scheduler] create scheduler client with endpoints [http://127.0.0.1:2379]
2022/04/19 12:12:39.465328 client.go:203: [info] [scheduler] switch leader, new-leader: http://127.0.0.1:2379, old-leader: 
2022/04/19 12:12:39.465349 client.go:124: [info] [][scheduler] init cluster id 7088162941824523262
2022/04/19 12:12:39.465670 client.go:305: [warning] [][scheduler] heartbeat stream get error: EOF 
2022/04/19 12:12:39.470378 node.go:148: [info] alloc first region id, regionID: 2, clusterID: 7088162941824523262, storeID: 1
2022/04/19 12:12:39.470544 node.go:153: [info] alloc first peer id for first region, peerID: 3, regionID: 2
2022/04/19 12:12:39.479944 node.go:60: [info] try bootstrap cluster, storeID: 1, region: id:2 region_epoch:<conf_ver:1 version:1 > peers:<id:3 store_id:1 > 
2022/04/19 12:12:39.482081 node.go:172: [info] bootstrap cluster ok, clusterID: 7088162941824523262
2022/04/19 12:12:39.486510 node.go:193: [info] start raft store node, storeID: 1
2022/04/19 12:12:39.486594 peer.go:41: [info] region id:2 region_epoch:<conf_ver:1 version:1 > peers:<id:3 store_id:1 >  create peer with ID 3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xca8c69]

goroutine 1 [running]:
github.com/pingcap-incubator/tinykv/raft.(*RawNode).Campaign(...)
        /root/tinykv/raft/rawnode.go:88
github.com/pingcap-incubator/tinykv/kv/raftstore.NewPeer(0x1, 0xc000322280, 0xc00025a000, 0xc0044c2080, 0xc00007f140, 0xc0044a5500, 0x2, 0x30, 0xc0044a54a0)
        /root/tinykv/kv/raftstore/peer.go:153 +0x429
github.com/pingcap-incubator/tinykv/kv/raftstore.createPeer(0x1, 0xc000322280, 0xc00007f140, 0xc00025a000, 0xc0044c2080, 0x0, 0x0, 0x0)
        /root/tinykv/kv/raftstore/peer.go:42 +0x145
github.com/pingcap-incubator/tinykv/kv/raftstore.(*Raftstore).loadPeers.func1(0xc00015aa20, 0x0, 0x0)
        /root/tinykv/kv/raftstore/raftstore.go:156 +0x38c
github.com/Connor1996/badger.(*DB).View(0xc000325680, 0xc000265ac8, 0x0, 0x0)
        /root/go/pkg/mod/github.com/!connor1996/badger@v1.5.1-0.20220222053432-2d2cbf472c77/transaction.go:546 +0x9d
github.com/pingcap-incubator/tinykv/kv/raftstore.(*Raftstore).loadPeers(0xc00008a040, 0xc0044c2000, 0x20, 0xc0044c0000, 0xc8d132, 0x1058b08)
        /root/tinykv/kv/raftstore/raftstore.go:123 +0x26d
github.com/pingcap-incubator/tinykv/kv/raftstore.(*Raftstore).start(0xc00008a040, 0xc00008a0c0, 0xc000322280, 0xc00025a000, 0x1040660, 0xc004416140, 0x1060740, 0xc00025c000, 0xc00008a080, 0xc8f480, ...)
        /root/tinykv/kv/raftstore/raftstore.go:252 +0x5ba
github.com/pingcap-incubator/tinykv/kv/raftstore.(*Node).startNode(0xc000014240, 0xc00025a000, 0x1040660, 0xc004416140, 0xc00008a080, 0x0, 0x0)
        /root/tinykv/kv/raftstore/node.go:194 +0x111
github.com/pingcap-incubator/tinykv/kv/raftstore.(*Node).Start(0xc000014240, 0x1058ad0, 0xc00003c118, 0xc00025a000, 0x1040660, 0xc004416140, 0xc00008a080, 0x0, 0x0)
        /root/tinykv/kv/raftstore/node.go:71 +0x177
github.com/pingcap-incubator/tinykv/kv/storage/raft_storage.(*RaftStorage).Start(0xc000340960, 0xc000340960, 0xf41e55)
        /root/tinykv/kv/storage/raft_storage/raft_server.go:199 +0x625
main.main()
        /root/tinykv/kv/main.go:57 +0x22b

**Comment by Connor1996** [comment]
You should finish the course to make it runnable
