### ISSUE TITLE
About Exactly-once and at least once feature of the raft module

### ISSUE THREAD

**Issue by xhnhill** [talent-plan/tinykv#411]
In project2, do we need to implement a raft module that satisfies at-least-once feature, or are we required to implement a raft model that satisfies exactly-once feature? I noticed that al-least-once could help to pass the test. But I am a little confused about whether at least once will influence the correctness of the upper layer? Or is there any remediation in the upper layer that will help to form exactly once?

**Comment by Connor1996** [comment]
Exactly-once is not a constraint for the raft module. It depends on how the upper layer is implemented. For the raftstore model in TinyKV, it keeps the exactly-once by persisting apply index.
