### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by bootjp** [talent-plan/tinykv#412]
There seems to be no license for this project. Is this intentional?

**Comment by bootjp** [comment]
I was implementing a TiKV compatible server for learning and research and discovered this project during my research.

I would like to use some of this project for learning and research, but I am hesitant to use this project because its license is unclear.

tinysql is licensed for Apache 2. It does not appear to exist in tinykv.
https://github.com/talent-plan/tinysql/blob/course/LICENSE
I would like to ask if this is intentionally not licensed.

**Comment by Connor1996** [comment]
Thanks for the mention, just didn't take into consideration the license before. Introduce Apache 2.0 now https://github.com/talent-plan/tinykv/pull/414

**Comment by bootjp** [comment]
Thank you!
