### ISSUE TITLE
Clarification of the content in project3b

### ISSUE THREAD

**Issue by xhnhill** [talent-plan/tinykv#413]
In the documentation of project3b, "Implement conf change in raftstore "  part
There is a sentence: It will be used to guarantee the latest region information under network isolation that two leaders in one Region.
It is confusing what kind of features it guarantees. Does it mean something could keep the latest region information?

**Comment by Connor1996** [comment]
Under network isolation, there may be two raft leader simultaneously (though different term). Both leaders would report region heartbeat to scheduler, then scheduler can relay on epoch to decide which one is the latest. Feel free to file a PR to elaborate the doc.
