### ISSUE TITLE
test-case疑问

### ISSUE THREAD

**Issue by NicoleRobin** [talent-plan/tinykv#434]
https://github.com/talent-plan/tinykv/blob/f251031837db8c286972568cd5108f5f694e98cb/kv/server/server_test.go#L199

这个测试用例是不是应该改为判断err是否等于KeyNotFound，因为前面已经执行过删除了，所以此时再去查询应该是key不存在的。

**Comment by virtuosoo** [comment]
我也觉得

**Comment by Connor1996** [comment]
Please check the comment of `GetCF()`

**Comment by NicoleRobin** [comment]
> 

OK, thank you for you advice, i will check this function's comment again.
