### ISSUE TITLE
Help: make error

### ISSUE THREAD

**Issue by wnz27** [talent-plan/tinykv#444]
❯ make
GO111MODULE=on go build  -tags codes -o bin/tinykv-server kv/main.go
go build github.com/DataDog/zstd: build constraints exclude all Go files in /Users/f27/go/pkg/mod/github.com/!data!dog/zstd@v1.5.2
make: *** [kv] Error 1

**Comment by Smityz** [comment]
ref: https://github.com/DataDog/zstd/issues/46
if you are using Ubuntu, you can try `sudo apt install gcc -y`

**Comment by wnz27** [comment]
> ref: [DataDog/zstd#46](https://github.com/DataDog/zstd/issues/46) if you are using Ubuntu, you can try `sudo apt install gcc -y`

emmmm.....maybe the problem cause by  i use m1
