### ISSUE TITLE
Why the Autograding keeps waiting

### ISSUE THREAD

**Issue by Ingsuifon** [talent-plan/tinykv#447]
In the Autograding stage, the job is always waiting for a runner to pick up, and reports failure on the second day. The output is like this:
```
Requested labels: self-hosted, X64
Job defined at: talent-plan/tinykv-XXX/.github/workflows/classroom.yml@refs/heads/course
Waiting for a runner to pick up this job...
```

**Comment by yan-dblinf** [comment]
+1

**Comment by yan-dblinf** [comment]
@Ingsuifon The issue can be resolved by adding self-hosted runners. Basically, your local host can pick up the CI job and execute the auto-grading. See the [doc](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners?learn=hosting_your_own_runners&learnProduct=actions#adding-a-self-hosted-runner-to-a-repository) for details.

**Comment by Ingsuifon** [comment]
@yan-dblinf Thank you for remembering this issue and reminding me!
