### ISSUE TITLE
Is there any typo?

### ISSUE THREAD

**Issue by elephas00** [talent-plan/tinykv#455]
I am recently debug at 3B, and when I reading the Destroy function at file kv/raftstore/peer.go, I found that there is a comment "write kv rocksdb first in case of restart happen between two write". 
The previous lab in tinky-kv seems never mention about rocksdb, while the TiKV mentioned. So I think there is a typo, and this comment should be modified to " write kv badgerDB first in case of restart happen between two write“.
![image](https://github.com/talent-plan/tinykv/assets/72189234/c1f044ce-4146-4fa1-8fa0-6423bce0bc00)

**Comment by Connor1996** [comment]
Yes, it's a typo. Should be `write kv badgerDB first in case of restart happen between two write`
